# ===== Server =====
server.port=9090

# ===== App info =====
spring.application.name=seu-student-blog

# ===== MongoDB =====
spring.mongodb.uri=mongodb+srv://user1:11753@spring-mongo.dgdoyrn.mongodb.net/seu-student-blog?appName=spring-mongo
# ===== Thymeleaf =====
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ===== File upload (featured images) =====
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=uploads/blog-images

# ===== Logging =====
logging.level.com.seu.studentblog=DEBUG
logging.level.org.springframework.security=INFO
